apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf2-config
  labels:
    epc-mode: upf2
data:
  upf2.yaml: |
    logger:
        file: /var/log/open5gs/upf2.log

    upf:
        pfcp:
           dev: {{ .Values.k8s.interface }}
        gtpu:
           dev: net2
           advertise: {{ .Values.k8s.upf2-advertise }}
        subnet:
          - addr: 10.46.0.1/16
            dnn: {{ .Values.dnn }}
